# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reads', '0050_auto_20170929_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniKraken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krakenstatus', models.CharField(max_length=1)),
                ('krakentaxid', models.IntegerField()),
                ('krakenseqlen', models.BigIntegerField()),
                ('krakenlca', models.TextField()),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minikrakread', to='reads.FastqRead')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minikrakrun', to='reads.MinIONRun')),
            ],
        ),
    ]
