# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minikraken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestKraken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff1', models.CharField(max_length=20)),
            ],
        ),
    ]
