# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minikraken', '0002_testkraken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minikraken',
            name='krakenseqlen',
        ),
        migrations.RemoveField(
            model_name='minikraken',
            name='krakenstatus',
        ),
        migrations.RemoveField(
            model_name='minikraken',
            name='krakentaxid',
        ),
    ]
