# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minikraken', '0003_auto_20171001_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='minikraken',
            name='krakenseqlen',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minikraken',
            name='krakenstatus',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minikraken',
            name='krakentaxid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
