# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0050_auto_20170929_1304'),
        ('minikraken', '0004_auto_20171001_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedKraken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('rootreads', models.IntegerField()),
                ('directreads', models.IntegerField()),
                ('rank', models.CharField(max_length=1)),
                ('NCBItaxid', models.IntegerField()),
                ('sci_name', models.CharField(max_length=128)),
                ('indentation', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsedkrakrun', to='reads.MinIONRun')),
            ],
        ),
        migrations.DeleteModel(
            name='TestKraken',
        ),
    ]
