# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minikraken', '0006_auto_20171001_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedkraken',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
