# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minikraken', '0007_parsedkraken_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedkraken',
            old_name='order',
            new_name='orderin',
        ),
    ]
