# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0050_auto_20170929_1304'),
        ('minikraken', '0008_auto_20171001_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedkraken',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodekrakrun', to='reads.Barcode'),
        ),
        migrations.AddField(
            model_name='parsedkraken',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typekrakrun', to='reads.FastqReadType'),
        ),
    ]
