# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0050_auto_20170929_1304'),
        ('minikraken', '0010_parsedkraken_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='minikraken',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minikrakbarcode', to='reads.Barcode'),
        ),
        migrations.AddField(
            model_name='minikraken',
            name='read_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minikraktype', to='reads.FastqReadType'),
        ),
    ]
