# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minikraken', '0011_auto_20171002_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minikraken',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='minikraken',
            name='read_type',
        ),
    ]
