FROM python:3.6
MAINTAINER Roberto Santos

ENV PYTHONUNBUFFERED 1

ENV MT_SECRET_KEY=''
ENV MT_DJANGO_DEBUG='True'
ENV MT_DB_USER='dba'
ENV MT_DB_PASS='dba'
ENV MT_DB_HOST='minotour_db'
ENV MT_DB_PORT='5432'
ENV MT_DB_NAME='minotour'
ENV MT_MAILGUN_ACCESS_KEY=''
ENV MT_MAILGUN_SERVER_NAME=''
ENV MT_TWITTOKEN=''
ENV MT_TWITTOKEN_SECRET=''
ENV MT_TWITCONSUMER_KEY=''
ENV MT_TWITCONSUMER_SECRET=''
ENV MT_REFERENCE_LOCATION='/home/mbzros/a/data'
ENV PATH="$HOME/a/opt/minimap2:$HOME/a/opt/bwa:$PATH"
ENV MT_MINIMAP2="~/a/opt/minimap2/minimap2"
ENV MT_BWA="~/a/opt/bwa/bwa"
#ENV MT_DB_ENGINE="django.db.backends.mysql"
ENV MT_DB_ENGINE="django.db.backends.postgresql"

RUN mkdir -p /var/lib/minotour/apps/minotourapp
RUN mkdir -p /var/lib/minotour/logs
RUN mkdir -p /var/lib/minotour/data

WORKDIR /var/lib/minotour/apps/minotourapp
# ADD requirements.txt /var/lib/minotour/apps/minotourapp
# ADD . /var/lib/minotour/apps/minotourapp
COPY . /var/lib/minotour/apps/minotourapp/
# COPY * /var/lib/minotour/apps/minotourapp/
RUN pip3 install -r requirements.txt

# RUN python manage.py makemigrations
# RUN python manage.py migrate

# EXPOSE 8000
# CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
