FROM python:3.6
MAINTAINER Roberto Santos

ENV PYTHONUNBUFFERED 1

ENV MT_SECRET_KEY=''
ENV MT_DJANGO_DEBUG='True'
ENV MT_DB_USER='root'
ENV MT_DB_PASS='test'
ENV MT_DB_HOST='minotour_db'
ENV MT_DB_PORT='3306'
ENV MT_DB_NAME='minotour'
ENV MT_MAILGUN_ACCESS_KEY=''
ENV MT_MAILGUN_SERVER_NAME=''
ENV MT_TWITTOKEN=''
ENV MT_TWITTOKEN_SECRET=''
ENV MT_TWITCONSUMER_KEY=''
ENV MT_TWITCONSUMER_SECRET=''
ENV MT_REFERENCE_LOCATION='/home/mbzros/a/data'
ENV MT_MINIMAP2="~/a/opt/minimap2/minimap2"
ENV MT_BWA="~/a/opt/bwa/bwa"
ENV MT_DB_ENGINE="django.db.backends.mysql"
# ENV MT_DB_ENGINE="django.db.backends.postgresql"

RUN mkdir -p /var/lib/minotour/apps/minotourapp /var/lib/minotour/logs /var/lib/minotour/data

WORKDIR /var/lib/minotour/apps/minotourapp

COPY . /var/lib/minotour/apps/minotourapp/

EXPOSE 8000

CMD ["sh", "entrypoint.sh"]
