dist: xenial
language: python # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6 # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6 on macOS"
      os: osx
      language: shell # 'language: python' is an error on Travis CI macOS
      python: 3.6

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -y -n primerSchemes -c conda-forge -c bioconda artic-tools
  - conda activate primerSchemes

script:
  # validate the schemes using artic-tools
  for i in */V*/*.primer.bed; do artic-tools validate_scheme $i; done;
