language: node_js

node_js:
  - 8
  - 10
  - 11
  - 12

env:
  - INSTALL=yarn
  - INSTALL=npm


matrix:
  fast_finish: true
  exclude:
    - node_js: 8
      env: INSTALL=yarn

install:
  - if [ "yarn" == $INSTALL ]; then yarn install; fi
  - if [ "npm" == $INSTALL ]; then npm install; fi

script:
  - echo 'Tests must be configured'
