# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reads', '0048_auto_20170914_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PafStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qsn', models.CharField(max_length=256)),
                ('qsl', models.IntegerField()),
                ('qs', models.IntegerField()),
                ('qe', models.IntegerField()),
                ('rs', models.CharField(max_length=1)),
                ('tsn', models.CharField(max_length=256)),
                ('tsl', models.IntegerField()),
                ('ts', models.IntegerField()),
                ('te', models.IntegerField()),
                ('nrm', models.IntegerField()),
                ('abl', models.IntegerField()),
                ('mq', models.IntegerField()),
                ('read_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafreadalignment', to='reads.FastqRead')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafalignemnts', to='reads.MinIONRun')),
            ],
        ),
        migrations.CreateModel(
            name='SamRoughCov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('chromosome', models.TextField()),
                ('position', models.IntegerField()),
                ('incdel', models.IntegerField()),
                ('read_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_type', to='reads.FastqReadType')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_runid', to='reads.MinIONRun')),
            ],
        ),
        migrations.CreateModel(
            name='SamStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samline', models.TextField()),
                ('read_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readalignment', to='reads.FastqRead')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runalignments', to='reads.MinIONRun')),
            ],
        ),
    ]
