# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pafstore',
            old_name='read_id',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='pafstore',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='samroughcov',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='samstore',
            old_name='read_id',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='samstore',
            old_name='run_id',
            new_name='run',
        ),
    ]
