# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0048_auto_20170914_1020'),
        ('alignment', '0002_auto_20170914_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PafRoughCov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('chromosome', models.TextField()),
                ('position', models.IntegerField()),
                ('incdel', models.IntegerField()),
                ('read_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_type', to='reads.FastqReadType')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_run', to='reads.MinIONRun')),
            ],
        ),
    ]
