# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0048_auto_20170914_1020'),
        ('alignment', '0003_pafroughcov'),
    ]

    operations = [
        migrations.AddField(
            model_name='pafroughcov',
            name='barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prc_barcode', to='reads.Barcode'),
        ),
        migrations.AlterField(
            model_name='pafroughcov',
            name='incdel',
            field=models.IntegerField(default=0),
        ),
    ]
