# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0004_auto_20170914_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pafroughcov',
            name='chromosome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafchromosome', to='reference.ReferenceLine'),
        ),
        migrations.AlterField(
            model_name='pafroughcov',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafreference', to='reference.ReferenceInfo'),
        ),
        migrations.AlterField(
            model_name='samroughcov',
            name='chromosome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samchromosome', to='reference.ReferenceLine'),
        ),
        migrations.AlterField(
            model_name='samroughcov',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samreference', to='reference.ReferenceInfo'),
        ),
    ]
