# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20170915_0709'),
        ('alignment', '0005_auto_20170915_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='pafstore',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pafstorereference', to='reference.ReferenceInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pafstore',
            name='tsn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafstorechromosome', to='reference.ReferenceLine'),
        ),
    ]
