# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0006_auto_20170915_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pafroughcov',
            old_name='incdel',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='pafroughcov',
            old_name='position',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='samroughcov',
            old_name='incdel',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='samroughcov',
            old_name='position',
            new_name='p',
        ),
    ]
