# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0049_auto_20170915_0717'),
        ('reference', '0004_auto_20170915_0709'),
        ('alignment', '0007_auto_20170916_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='PafSummaryCov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.BigIntegerField()),
                ('cumu_length', models.BigIntegerField()),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_barcode', to='reads.Barcode')),
                ('chromsome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_chromosome', to='reference.ReferenceLine')),
                ('read_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_type', to='reads.FastqReadType')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_reference', to='reference.ReferenceInfo')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary', to='reads.MinIONRun')),
            ],
        ),
    ]
