# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0049_auto_20170915_0717'),
        ('alignment', '0008_pafsummarycov'),
    ]

    operations = [
        migrations.AddField(
            model_name='pafstore',
            name='read_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pafstoretype', to='reads.FastqReadType'),
            preserve_default=False,
        ),
    ]
