# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0009_pafstore_read_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pafsummarycov',
            name='cumu_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pafsummarycov',
            name='read_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
