# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0010_auto_20170916_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pafsummarycov',
            old_name='chromsome',
            new_name='chromosome',
        ),
    ]
