# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0062_jobtype_transcriptome'),
        ('reference', '0005_referenceinfo_transcripts'),
        ('alignment', '0011_auto_20170916_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PafRoughCov_transcriptome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
                ('i', models.IntegerField(default=0)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prc_barcode_transcriptome', to='reads.Barcode')),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafchromosome_transcriptome', to='reference.ReferenceLine')),
                ('read_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_type_transcriptome', to='reads.FastqReadType')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafreference_transcriptome', to='reference.ReferenceInfo')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_run_transcriptome', to='reads.MinIONRun')),
            ],
        ),
        migrations.CreateModel(
            name='PafStore_transcriptome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qsn', models.CharField(max_length=256)),
                ('qsl', models.IntegerField()),
                ('qs', models.IntegerField()),
                ('qe', models.IntegerField()),
                ('rs', models.CharField(max_length=1)),
                ('tsl', models.IntegerField()),
                ('ts', models.IntegerField()),
                ('te', models.IntegerField()),
                ('nrm', models.IntegerField()),
                ('abl', models.IntegerField()),
                ('mq', models.IntegerField()),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafreadalignment_transcriptome', to='reads.FastqRead')),
                ('read_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafstoretype_transcriptome', to='reads.FastqReadType')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafstorereference_transcriptome', to='reference.ReferenceInfo')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafalignemnts_transcriptome', to='reads.MinIONRun')),
                ('tsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pafstorechromosome_transcriptome', to='reference.ReferenceLine')),
            ],
        ),
        migrations.CreateModel(
            name='PafSummaryCov_transcriptome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.BigIntegerField(default=0)),
                ('cumu_length', models.BigIntegerField(default=0)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_barcode_transcriptome', to='reads.Barcode')),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_chromosome_transcriptome', to='reference.ReferenceLine')),
                ('read_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_type_transcriptome', to='reads.FastqReadType')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_reference_transcriptome', to='reference.ReferenceInfo')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_summary_transcriptome', to='reads.MinIONRun')),
            ],
        ),
    ]
