# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceLines',
            new_name='ReferenceLine',
        ),
    ]
