# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20170914_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinfo',
            name='totalrefleN',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='referenceline',
            name='chromosome_length',
            field=models.BigIntegerField(),
        ),
    ]
