# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20170915_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceinfo',
            name='transcripts',
            field=models.BooleanField(default=False),
        ),
    ]
