# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FastqRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_id', models.CharField(max_length=64)),
                ('read', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('barcode', models.CharField(max_length=32)),
                ('sequence', models.TextField()),
                ('quality', models.TextField()),
                ('is_pass', models.BooleanField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FastqReadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MinION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minION_name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minIONs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinIONControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=256)),
                ('custom', models.CharField(blank=True, max_length=256, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('minION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minioncontrol', to='reads.MinION')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlcontrol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinIONEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinIONEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MinIONmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minKNOW_message', models.CharField(max_length=256)),
                ('minKNOW_identifier', models.CharField(max_length=256)),
                ('minKNOW_severity', models.CharField(max_length=64)),
                ('minKNOW_message_timestamp', models.DateTimeField()),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reads.MinION')),
            ],
        ),
        migrations.CreateModel(
            name='MinIONRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=64)),
                ('run_id', models.CharField(max_length=64)),
                ('is_barcoded', models.BooleanField(default=False)),
                ('minION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minionrun', to='reads.MinION')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinIONRunStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('event_yield', models.IntegerField(default=0)),
                ('asic_temp', models.FloatField(default=0)),
                ('heat_sink_temp', models.FloatField(default=0)),
                ('voltage_value', models.FloatField(default=0)),
                ('mean_ratio', models.FloatField(default=0)),
                ('open_pore', models.FloatField(default=0)),
                ('in_strand', models.FloatField(default=0)),
                ('multiple', models.IntegerField(default=0)),
                ('unavailable', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('adapter', models.IntegerField(default=0)),
                ('pending_mux_change', models.IntegerField(default=0)),
                ('unclassified', models.IntegerField(default=0)),
                ('below', models.IntegerField(default=0)),
                ('unblocking', models.IntegerField(default=0)),
                ('above', models.IntegerField(default=0)),
                ('good_single', models.IntegerField(default=0)),
                ('saturated', models.IntegerField(default=0)),
                ('inrange', models.IntegerField(default=0)),
                ('strand', models.IntegerField(default=0)),
                ('minKNOW_read_count', models.IntegerField(default=0)),
                ('minKNOW_histogram_values', models.TextField(blank=True, null=True)),
                ('minKNOW_histogram_bin_width', models.IntegerField(default=900)),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentrunstats', to='reads.MinION')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RunStats', to='reads.MinIONRun')),
            ],
        ),
        migrations.CreateModel(
            name='MinIONRunStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minKNOW_current_script', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_sample_name', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_exp_script_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_flow_cell_id', models.CharField(blank=True, max_length=64, null=True)),
                ('minKNOW_version', models.CharField(blank=True, max_length=64, null=True)),
                ('minKNOW_run_name', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_hash_run_id', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_script_run_id', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_real_sample_rate', models.IntegerField(blank=True, null=True)),
                ('minKNOW_asic_id', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_start_time', models.DateTimeField(blank=True, null=True)),
                ('minKNOW_colours_string', models.TextField(blank=True, null=True)),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentrundetails', to='reads.MinION')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RunDetails', to='reads.MinIONRun')),
            ],
        ),
        migrations.CreateModel(
            name='MinIONScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('experiment_type', models.CharField(blank=True, max_length=256, null=True)),
                ('base_calling', models.NullBooleanField()),
                ('flow_cell', models.CharField(blank=True, max_length=256, null=True)),
                ('kit', models.CharField(blank=True, max_length=256, null=True)),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='reads.MinION')),
            ],
        ),
        migrations.CreateModel(
            name='MinIONStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minKNOW_status', models.CharField(max_length=64)),
                ('minKNOW_current_script', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_sample_name', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_exp_script_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_flow_cell_id', models.CharField(blank=True, max_length=64, null=True)),
                ('minKNOW_run_name', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_hash_run_id', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_script_run_id', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_real_sample_rate', models.IntegerField(blank=True, null=True)),
                ('minKNOW_asic_id', models.CharField(blank=True, max_length=256, null=True)),
                ('minKNOW_total_drive_space', models.FloatField(blank=True, null=True)),
                ('minKNOW_disk_space_till_shutdown', models.FloatField(blank=True, null=True)),
                ('minKNOW_disk_available', models.FloatField(blank=True, null=True)),
                ('minKNOW_warnings', models.BooleanField(default=False)),
                ('minION', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currentdetails', to='reads.MinION')),
            ],
        ),
        migrations.CreateModel(
            name='RunStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('total_length', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.CreateModel(
            name='RunStatisticBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('total_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=32)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.CreateModel(
            name='RunSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('run_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runsummary', to='reads.MinIONRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.CreateModel(
            name='RunSummaryBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=32)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.AddField(
            model_name='minionmessages',
            name='run_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runmessages', to='reads.MinIONRun'),
        ),
        migrations.AddField(
            model_name='minionevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONEventType'),
        ),
        migrations.AddField(
            model_name='minionevent',
            name='minION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reads.MinION'),
        ),
        migrations.AddField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinIONRun'),
        ),
        migrations.AddField(
            model_name='fastqread',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType'),
        ),
        migrations.AlterUniqueTogether(
            name='minionmessages',
            unique_together=set([('minION', 'run_id', 'minKNOW_message_timestamp')]),
        ),
    ]
