# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=64)),
                ('run_id', models.CharField(max_length=64)),
                ('read', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('barcode', models.CharField(max_length=32)),
            ],
        ),
    ]
