# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastqRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_id', models.CharField(max_length=64)),
                ('read', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('barcode', models.CharField(max_length=32)),
                ('sequence', models.TextField()),
                ('quality', models.TextField()),
                ('status', models.BooleanField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FastqReadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='minionrun',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='minionrun',
            name='read',
        ),
        migrations.RemoveField(
            model_name='minionrun',
            name='start_time',
        ),
        migrations.AddField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinionRun'),
        ),
        migrations.AddField(
            model_name='fastqread',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType'),
        ),
    ]
