# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minionrunstats',
            old_name='eventyield',
            new_name='event_yield',
        ),
        migrations.RenameField(
            model_name='minionrunstats',
            old_name='sampletime',
            new_name='sample_time',
        ),
    ]
