# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastqread',
            options={'verbose_name': 'FASTQ Read', 'verbose_name_plural': 'FASTQ Read'},
        ),
        migrations.AlterModelOptions(
            name='fastqreadtype',
            options={'verbose_name': 'FASTQ Read Type', 'verbose_name_plural': 'FASTQ Read Types'},
        ),
        migrations.AlterModelOptions(
            name='minion',
            options={'verbose_name': 'MinION', 'verbose_name_plural': 'MinIONs'},
        ),
        migrations.AlterModelOptions(
            name='minioncontrol',
            options={'verbose_name': 'MinION Control', 'verbose_name_plural': 'MinION Controls'},
        ),
        migrations.AlterModelOptions(
            name='minionevent',
            options={'verbose_name': 'MinION Event', 'verbose_name_plural': 'MinION Events'},
        ),
        migrations.AlterModelOptions(
            name='minioneventtype',
            options={'verbose_name': 'MinION Event Type', 'verbose_name_plural': 'MinION Event Types'},
        ),
        migrations.AlterModelOptions(
            name='minionmessages',
            options={'verbose_name': 'MinION Message', 'verbose_name_plural': 'MinION Messages'},
        ),
        migrations.AlterModelOptions(
            name='minionrun',
            options={'verbose_name': 'MinION Run', 'verbose_name_plural': 'MinION Runs'},
        ),
        migrations.AlterModelOptions(
            name='minionrunstats',
            options={'verbose_name': 'MinION Run Stats', 'verbose_name_plural': 'MinION Run Stats'},
        ),
        migrations.AlterModelOptions(
            name='minionrunstatus',
            options={'verbose_name': 'MinION Run Status', 'verbose_name_plural': 'MinION Run Status'},
        ),
        migrations.AlterModelOptions(
            name='minionscripts',
            options={'verbose_name': 'MinION Script', 'verbose_name_plural': 'MinION Scripts'},
        ),
        migrations.AlterModelOptions(
            name='minionstatus',
            options={'verbose_name': 'MinION Status', 'verbose_name_plural': 'MinION Status'},
        ),
        migrations.AlterModelOptions(
            name='runstatistic',
            options={'verbose_name': 'Run Statistics', 'verbose_name_plural': 'Run Statistics'},
        ),
        migrations.AlterModelOptions(
            name='runstatisticbarcode',
            options={'verbose_name': 'Run Statistics Barcode', 'verbose_name_plural': 'Run Statistics Barcodes'},
        ),
        migrations.AlterModelOptions(
            name='runsummary',
            options={'verbose_name': 'Run Summary', 'verbose_name_plural': 'Run Summaries'},
        ),
        migrations.AlterModelOptions(
            name='runsummarybarcode',
            options={'verbose_name': 'Run Summary Barcode', 'verbose_name_plural': 'Run Summary Barcodes'},
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runsummaries', to='reads.MinIONRun'),
        ),
    ]
