# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0002_auto_20170629_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runsummariesbarcodes', to='reads.MinIONRun'),
        ),
    ]
