# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0002_auto_20170512_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastqread',
            old_name='status',
            new_name='is_pass',
        ),
    ]
