# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0003_auto_20170516_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('total_length', models.IntegerField()),
                ('max_length', models.IntegerField()),
                ('min_length', models.IntegerField()),
                ('average_length', models.DecimalField(decimal_places=2, max_digits=11)),
                ('number_of_reads', models.IntegerField()),
                ('number_of_channels', models.IntegerField()),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinionRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
    ]
