# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0003_auto_20170718_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minionrunstats',
            name='event_yield',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='total_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='total_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='total_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='total_length',
            field=models.BigIntegerField(default=0),
        ),
    ]
