# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0003_auto_20170613_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrunstats',
            name='above',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='adapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='below',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='good_single',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='inrange',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='pending_mux_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='saturated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='strand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='unavailable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='unblocking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='unclassified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minionrunstats',
            name='unknown',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
