# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0004_auto_20170614_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minionrunstats',
            name='above',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='adapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='asic_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='below',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='event_yield',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='good_single',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='heat_sink_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='in_strand',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='inrange',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='mean_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='multiple',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='open_pore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='pending_mux_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='saturated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='strand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='unavailable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='unblocking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='unclassified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='unknown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minionrunstats',
            name='voltage_value',
            field=models.FloatField(default=0),
        ),
    ]
