# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0004_runstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrun',
            name='is_barcoded',
            field=models.BooleanField(default=False),
        ),
    ]
