# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reads', '0005_minionrun_is_barcoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrun',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
