# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0005_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastqread',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastqread',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='pass_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='pass_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='pass_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='pass_length',
            field=models.BigIntegerField(default=0),
        ),
    ]
