# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0006_auto_20170723_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrunstats',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
