# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0006_minionrun_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minionrun',
            name='barcode',
        ),
    ]
