# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0006_auto_20170614_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runsummary', to='reads.MinIONRun'),
        ),
    ]
