# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0007_minionrunstats_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='JobMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskname', to='reads.Job')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runjobs', to='reads.MinIONRun')),
            ],
        ),
    ]
