# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0007_remove_minionrun_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunStatisticBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('total_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=32)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinionRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.CreateModel(
            name='RunSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinionRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.CreateModel(
            name='RunSummaryBarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_length', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=32)),
                ('pass_length', models.IntegerField(default=0)),
                ('pass_max_length', models.IntegerField(default=0)),
                ('pass_min_length', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(default=0)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinionRun')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType')),
            ],
        ),
        migrations.RemoveField(
            model_name='runstatistic',
            name='average_length',
        ),
        migrations.RemoveField(
            model_name='runstatistic',
            name='number_of_channels',
        ),
        migrations.RemoveField(
            model_name='runstatistic',
            name='number_of_reads',
        ),
        migrations.AddField(
            model_name='runstatistic',
            name='pass_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runstatistic',
            name='pass_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runstatistic',
            name='pass_max_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runstatistic',
            name='pass_min_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runstatistic',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinionRun'),
        ),
    ]
