# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0008_job_jobmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaster',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobmaster',
            name='var1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobmaster',
            name='var2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobmaster',
            name='var3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
