# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0008_auto_20170519_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstatistic',
            name='max_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='min_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='total_length',
            field=models.IntegerField(default=0),
        ),
    ]
