# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0009_auto_20170614_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionevent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minionevent',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
