# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reads', '0009_auto_20170520_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minION_name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minIONs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinIONEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MinIONEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AddField(
            model_name='minionevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONEventType'),
        ),
        migrations.AddField(
            model_name='minionevent',
            name='minION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reads.MinION'),
        ),
        migrations.AddField(
            model_name='minionrun',
            name='minION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reads.MinION'),
        ),
    ]
