# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0009_auto_20170724_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaster',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
