# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0010_auto_20170526_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
    ]
