# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0010_jobmaster_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
                ('rname', models.CharField(max_length=512)),
                ('pos', models.BigIntegerField()),
                ('mapq', models.IntegerField()),
                ('cigar', models.CharField(max_length=5)),
                ('rnext', models.CharField(max_length=512)),
                ('pnext', models.IntegerField()),
                ('tlen', models.IntegerField()),
                ('seq', models.CharField(max_length=5)),
                ('qual', models.CharField(max_length=5)),
                ('n_m', models.CharField(max_length=512)),
                ('m_d', models.CharField(max_length=512)),
                ('a_s', models.CharField(max_length=512)),
                ('x_s', models.CharField(max_length=512)),
                ('read_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readalignment', to='reads.FastqRead')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runalignments', to='reads.MinIONRun')),
            ],
        ),
    ]
