# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0011_auto_20170614_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minionstatus',
            name='minKNOW_histogram_bin_width',
        ),
        migrations.RemoveField(
            model_name='minionstatus',
            name='minKNOW_histogram_values',
        ),
        migrations.AddField(
            model_name='minionrunstatus',
            name='minKNOW_histogram_bin_width',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='minionrunstatus',
            name='minKNOW_histogram_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
