# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0012_auto_20170724_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sam',
            name='a_s',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='cigar',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='m_d',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='mapq',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='n_m',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='pnext',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='qual',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='rnext',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='tlen',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='x_s',
        ),
    ]
