# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0013_auto_20170724_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sam',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='sam',
            name='rname',
        ),
    ]
