# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0013_auto_20170614_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minionmessages',
            name='minION',
        ),
        migrations.DeleteModel(
            name='MinIONmessages',
        ),
    ]
