# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0014_auto_20170614_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinIONmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minKNOW_message', models.CharField(max_length=256)),
                ('minKNOW_severity', models.CharField(max_length=64)),
                ('minKNOW_message_timestamp', models.DateTimeField()),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reads.MinION')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runmessages', to='reads.MinIONRun')),
            ],
        ),
    ]
