# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0014_auto_20170527_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinIONScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('experiment_type', models.CharField(blank=True, max_length=256, null=True)),
                ('base_calling', models.NullBooleanField()),
                ('flow_cell', models.CharField(blank=True, max_length=256, null=True)),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='reads.MinION')),
            ],
        ),
        migrations.AlterField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
    ]
