# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0014_auto_20170724_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sam',
            new_name='SamStore',
        ),
    ]
