# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0015_auto_20170724_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samstore',
            name='read_id',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='run_id',
        ),
        migrations.DeleteModel(
            name='SamStore',
        ),
    ]
