# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0015_minionmessages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='minionmessages',
            unique_together=set([('minION', 'run_id', 'minKNOW_message_timestamp')]),
        ),
    ]
