# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0016_auto_20170528_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinIONStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minKNOW_status', models.CharField(max_length=64)),
                ('minKNOW_current_script', models.CharField(max_length=256)),
                ('minKNOW_sample_name', models.CharField(max_length=256)),
                ('minKNOW_flow_cell_id', models.CharField(max_length=64)),
                ('minKNOW_run_name', models.CharField(max_length=256)),
                ('minKNOW_voltage_offset', models.IntegerField()),
                ('minKNOW_yield', models.IntegerField()),
                ('minKNOW_total_drive_space', models.FloatField()),
                ('minKNOW_disk_space_till_shutdown', models.FloatField()),
                ('minKNOW_warnings', models.BooleanField(default=False)),
                ('minION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentdetails', to='reads.MinION')),
            ],
        ),
        migrations.AlterField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
    ]
