# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0016_auto_20170724_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runalignments', to='reads.MinIONRun')),
            ],
        ),
    ]
