# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0016_auto_20170614_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionmessages',
            name='minKNOW_identifier',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
