# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0017_auto_20170528_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastqread',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_current_script',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_disk_space_till_shutdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_flow_cell_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_run_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_sample_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_total_drive_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_voltage_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minionstatus',
            name='minKNOW_yield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runstatistic',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runstatisticbarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummary',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
        migrations.AlterField(
            model_name='runsummarybarcode',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun'),
        ),
    ]
