# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0017_samstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='samstore',
            name='read_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readalignment', to='reads.FastqRead'),
            preserve_default=False,
        ),
    ]
