# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0017_minionmessages_minknow_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minionmessages',
            name='run_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runmessages', to='reads.MinIONRun'),
        ),
    ]
