# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0018_samstore_read_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='samstore',
            name='as',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='cigar',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='md',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='mapq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='nm',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='pnext',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='pos',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='qual',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='rname',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='rnext',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='seq',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='tlen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samstore',
            name='xs',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
    ]
