# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0019_auto_20170614_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionstatus',
            name='run_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MinIONRunID', to='reads.MinIONRun'),
        ),
    ]
