# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0020_auto_20170724_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samstore',
            old_name='zs',
            new_name='a_s',
        ),
    ]
