# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0021_auto_20170724_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samstore',
            old_name='a_s',
            new_name='ass',
        ),
    ]
