# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0021_auto_20170616_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrunstatus',
            name='minKNOW_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
