# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0022_minionrunstatus_minknow_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrunstatus',
            name='minKNOW_colours_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
