# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0022_auto_20170724_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samstore',
            name='md',
            field=models.TextField(),
        ),
    ]
