# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0023_auto_20170724_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samstore',
            name='ass',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='cigar',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='mapq',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='md',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='nm',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='pnext',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='qual',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='rname',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='rnext',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='tlen',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='xs',
        ),
        migrations.AddField(
            model_name='samstore',
            name='samline',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
