# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0024_minioncontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minioncontrol',
            name='custom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
