# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0025_channelsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistogramSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_width', models.BigIntegerField()),
                ('read_count', models.BigIntegerField()),
                ('read_length', models.BigIntegerField()),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun')),
            ],
        ),
    ]
