# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0025_auto_20170621_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minioncontrol',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
