# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0026_auto_20170621_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minioncontrol',
            name='owner',
        ),
    ]
