# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0026_histogramsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='histogramsummary',
            name='read_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reads.FastqReadType'),
            preserve_default=False,
        ),
    ]
