# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0027_remove_minioncontrol_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minioncontrol',
            name='completedate',
        ),
        migrations.AddField(
            model_name='minioncontrol',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
