# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0028_useroptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extendedopts', to=settings.AUTH_USER_MODEL),
        ),
    ]
