# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0029_auto_20170729_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extendedopts', to=settings.AUTH_USER_MODEL),
        ),
    ]
