# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0030_minioncontrol_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrunstatus',
            name='minKNOW_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
