# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0030_auto_20170729_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrun',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
