# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0031_minionrun_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=32)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reads.MinIONRun')),
            ],
        ),
    ]
