# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0032_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsummary',
            name='read_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelsummary',
            name='read_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='histogramsummary',
            name='read_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='histogramsummary',
            name='read_length',
            field=models.BigIntegerField(default=0),
        ),
    ]
