# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0033_auto_20170808_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='barcode',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='barcode',
            old_name='run_id',
            new_name='run',
        ),
        migrations.AddField(
            model_name='histogramsummary',
            name='barcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reads.Barcode'),
            preserve_default=False,
        ),
    ]
