# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0034_auto_20170824_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Read',
        ),
    ]
