# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0035_delete_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='reads.MinIONRun'),
        ),
    ]
