# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0036_auto_20170827_0748'),
        ('reads', '0034_minionrunstatus_minknow_computer'),
    ]

    operations = [
    ]
