# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0039_fastqread_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runstatisticbarcode',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='runsummarybarcode',
            name='barcode',
        ),
    ]
