# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('reads', '0037_merge_20170831_1009'),
        #('reads', '0041_auto_20170904_1141'),
        ('reads', '0042_merge_20170904_1339'),
    ]

    operations = [
    ]
