# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('reads', '0037_merge_20170831_1009'),
        ('reads', '0041_auto_20170904_1141'),
    ]

    operations = [
    ]
