# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0042_merge_20170904_2024'),
        #('reads', '0042_merge_20170904_1339'),
    ]

    operations = [
    ]
