# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0047_pafstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pafstore',
            name='read_id',
        ),
        migrations.RemoveField(
            model_name='pafstore',
            name='run_id',
        ),
        migrations.RemoveField(
            model_name='samroughcov',
            name='read_type',
        ),
        migrations.RemoveField(
            model_name='samroughcov',
            name='run_id',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='read_id',
        ),
        migrations.RemoveField(
            model_name='samstore',
            name='run_id',
        ),
        migrations.DeleteModel(
            name='PafStore',
        ),
        migrations.DeleteModel(
            name='SamRoughCov',
        ),
        migrations.DeleteModel(
            name='SamStore',
        ),
    ]
