# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0048_auto_20170914_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobmaster',
            name='var1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencejob', to='reference.ReferenceInfo'),
        ),
    ]
