# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20170915_0709'),
        ('reads', '0049_auto_20170915_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmaster',
            old_name='var2',
            new_name='last_read',
        ),
        migrations.RemoveField(
            model_name='jobmaster',
            name='var1',
        ),
        migrations.AddField(
            model_name='jobmaster',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencejob', to='reference.ReferenceInfo'),
        ),
    ]
