# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0050_auto_20170929_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobname',
            new_name='name',
        ),
    ]
