# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0051_auto_20171010_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='JobType',
        ),
    ]
