# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0053_auto_20171010_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='minionrun',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
