# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:35
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias


    JobType = apps.get_model("reads", "JobType")

    JobType.objects.using(db_alias).bulk_create([
        JobType(name="Assembly", private=True)
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.

    db_alias = schema_editor.connection.alias

    JobType = apps.get_model("reads", "JobType")

    JobType.objects.using(db_alias).filter(name="Assembly").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0055_initial_data'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
