# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('reads', '0056_auto_20171026_1235'),
        ('reads', '0056_jobtype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmaster',
            old_name='var3',
            new_name='tempfile_name',
        ),
    ]
