# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('reads', '0056_jobtype_description'),
        ('reads', '0057_auto_20171026_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='reference',
            field=models.BooleanField(default=False),
        ),
    ]
