# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0057_jobtype_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='readcount',
            field=models.BooleanField(default=False),
        ),
    ]
