# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0058_jobtype_readcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaster',
            name='read_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
