# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0059_jobmaster_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
