# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0061_auto_20171026_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='transcriptome',
            field=models.BooleanField(default=False),
        ),
    ]
