# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0062_jobtype_transcriptome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
