# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0063_flowcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowCellRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcelldetails', to='reads.FlowCell')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcellrun', to='reads.MinIONRun')),
            ],
        ),
    ]
