# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0064_flowcellruns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlowCellRuns',
            new_name='FlowCellRun',
        ),
    ]
