# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0057_jobtype_reference'),
        ('reads', '0066_flowcell_owner'),
        ('reads', '0057_auto_20171026_1301'),
    ]

    operations = [
    ]
