# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0066_flowcell_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastqread',
            name='read_id',
            field=models.CharField(max_length=96),
        ),
    ]
