# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0067_auto_20171114_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='tab_id',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='tab_title',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
