# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0069_auto_20171114_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='tab_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
