# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0070_jobtype_tab_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='tab_id',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='tab_position',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='tab_title',
        ),
    ]
