# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reads', '0055_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nreads', models.IntegerField()),
                ('ncontigs', models.IntegerField()),
                ('maxlen', models.IntegerField()),
                ('minlen', models.IntegerField()),
                ('totlen', models.IntegerField()),
                ('n50len', models.IntegerField()),
                ('meanlen', models.IntegerField()),
                ('gfaformat', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfaassembly', to='reads.MinIONRun')),
            ],
        ),
    ]
