# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0068_auto_20171109_2211'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfaSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nreads', models.IntegerField()),
                ('ncontigs', models.IntegerField()),
                ('maxlen', models.IntegerField()),
                ('minlen', models.IntegerField()),
                ('totlen', models.IntegerField()),
                ('n50len', models.IntegerField()),
                ('meanlen', models.IntegerField()),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodegfasummary', to='reads.Barcode')),
                ('readtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readtypegfasummary', to='reads.FastqReadType')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfasummaryrun', to='reads.MinIONRun')),
            ],
        ),
        migrations.RemoveField(
            model_name='gfastore',
            name='maxlen',
        ),
        migrations.RemoveField(
            model_name='gfastore',
            name='meanlen',
        ),
        migrations.RemoveField(
            model_name='gfastore',
            name='minlen',
        ),
        migrations.RemoveField(
            model_name='gfastore',
            name='n50len',
        ),
        migrations.RemoveField(
            model_name='gfastore',
            name='ncontigs',
        ),
        migrations.RemoveField(
            model_name='gfastore',
            name='totlen',
        ),
        migrations.AddField(
            model_name='gfastore',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodegfastore', to='reads.Barcode'),
        ),
        migrations.AddField(
            model_name='gfastore',
            name='readtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readtypegfastore', to='reads.FastqReadType'),
        ),
        migrations.AlterField(
            model_name='gfastore',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfastorerun', to='reads.MinIONRun'),
        ),
    ]
